{% set name = "pyasn1" %}
{% set version = "0.4.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "fb81622d8f3509f0026b0683fe90fea27be7284d3826a5f2edf97f69151ab0fc" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pyasn1
    - pyasn1.codec
    - pyasn1.codec.ber
    - pyasn1.codec.cer
    - pyasn1.codec.der
    - pyasn1.codec.native
    - pyasn1.compat
    - pyasn1.type

about:
  home: https://github.com/etingof/pyasn1
  license: BSD 2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'ASN.1 types and codecs'
  description: |
    Pure-Python implementation of ASN.1 types and DER/BER/CER codecs (X.208)
  doc_url: http://pyasn1.sourceforge.net/
  doc_source_url: https://github.com/etingof/pyasn1/blob/master/doc/source/contents.rst
  dev_url: https://github.com/etingof/pyasn1

extra:
  recipe-maintainers:
    - pmlandwehr
