{% set name = "pyasn1" %}
{% set version = "0.6.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c447d8431c947fe4c8febc4ed9e760bc29011a5b01e5c74b67025bd9fb8ce81

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

{% set skip_tests = "" %}
# E PermissionError: [WinError 32] The process cannot access the file because it is
# being used by another process: 'C:\\Users\\TAE497~1\\AppData\\Local\\Temp\\tmppd88ixif.zip'
{% set skip_tests = '-k "not (BinaryFileTestCase or CompressedFilesTestCase)"' %}  # [win]

test:
  source_files:
    - tests
  imports:
    - pyasn1
    - pyasn1.codec
    - pyasn1.codec.ber
    - pyasn1.codec.cer
    - pyasn1.codec.der
    - pyasn1.compat
    - pyasn1.type
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v {{ skip_tests }} tests

about:
  home: https://github.com/pyasn1/pyasn1
  license: BSD-2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: ASN.1 types and codecs
  description: |
    Pure-Python implementation of ASN.1 types and DER/BER/CER codecs (X.208)
  doc_url: https://pyasn1.readthedocs.io
  dev_url: https://github.com/pyasn1/pyasn1

extra:
  recipe-maintainers:
    - pmlandwehr
