travis:
  secure:
    BINSTAR_TOKEN: APcTwSpFOmWDhgMRLr0dzB/IICvuHYz2FU3GG6PUtjqGmU2zKUPxglxFkPfwxqbrhkAlkTKHOphtZcf6Zs56xWaa7SqrzW7+14hHASWJdsqllIkMDqBkDxoQELGgA4+s9LFUN/e6tlCOB0A6s7Oqu/YCihf+XPVh3K71o5vLTWCHD7NDkCNK5gHASlE15L0F9qV0e6H7nN8kOfjFlhL7QcyrOPS4+K1DAMC9pWKyY5ODjH8/h31KpCcKlHlT6R7aB4oMftWtA8rlXXU7U6uod+NiIb4lPXX+XCDL6JlZaTnh+rXWr/brXNJA8d5KqBGxZMhm8RG5NMbddIej47wGnMdgisobHQvxDTROi5D2dKvMnnMU/AmO4lNWd0EjsAVyOAw7cSlug7QovXKf/+VASntidGb1kbayUR8bieLmvbpqmDCY7VdIMIRIwhQxGO0hRj+4Uq4ea7Pp0R2vg5Y6xyiymC0p6JJCBwyNiLOdJeCQf+3X7yuW2Qf6C5cjWKGEvCUtYgJ4jizigyYCsdPpA73iO6Npt8i1KZzgejPFSd8ja91U6sGTDfCUw/Zb39lxuk236bjxR/GnT+bmqCLJuDS20PqmQmgv2fWFDZroxurfVJioKeU9zd74VlMF5m6AfwPe8weiUfwDWzCUacg2l2Ru4gHSAig8kqYoKdM8M64=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
