travis:
  secure:
    BINSTAR_TOKEN: PTtufi1En2dXQ048dZa/zXN2PwceRJ8DCRejBc3H1Qx7Tk+3n1H0daan7Z4Net415K3TBPihUQMxkCVj+d/yzTWuxq4H4UW2QmkH/sBOdaewf43FZf6Dsmsr8j5kaL+dLG5kYxOhf/gSF2Zo9+UCfTsb+byhjkBe5qcBeoGllYY/NiScRnmcwgk+A9AbWIFuV1YPRhN5iRZbpuZNFtfe6GrYbrPRNQv65DBvqYcMQOHUICudq5IODnXakbSF9UlYl6ZdHaCFc+uboOg85ELwTz8c2KVdLTv+Q5/jv+BF7dRUKV9JcBnwMVQEfW/PQnZBEP6GWbVof02aoSeQIdarkngGAzfeVz5zGAbSTHaoXp7o8hRm3fizicaSPRDXuhYiwnW8SPg5yuFR67pJfutBRBWcekgGL1tLzeG174f2v6qh6IGCkmBw2REYyynoJZWNnSqLEez/Rolu39amXSiADG/KQb4Z9D/pV4R2XbYiUTEZpKARGb+ajlxEgnYAKYaELAmla4ji6sdagCK5CicGg1UhwnJtEhfrrtjyFTqJ7wfWeRGA1OjaAGZi/FDvFgcT17o6+7mELe14T++PHMevDJPyBR4gRNU8da/v123ZyjUw9LsRsORspwbSh7b1lklJuFz9M+muQY+y2dF2b5Bu8KFbYubLIZvqct9zi5VMHgM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
